 services:
  cadotour:
    image: docker.promogi.fr/romain.jamet/cadotour:f1d77f6a
    restart: always

  proxy:
    image: docker.promogi.fr/neogi/infra/nginx-proxy:latest
    restart: always
    ports:
      - 443:443
    environment:
      NGINX_SERVER_NAME: cadotour.promogi.fr
      NGINX_PROXY: http://cadotour:80
